sudo: required
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
services:
  - docker
before_install:
  - docker --version
  - docker-compose --version
  - docker-compose up -d
  - |
      if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
        rustup component add clippy
      fi
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f cargo-travis;
        export PATH=$HOME/.cargo/bin:$PATH;
      fi
script:
  - RUST_BACKTRACE=1 cargo test --all --verbose
  - cargo test --package clickhouse-rs --features tokio,tokio_io --no-default-features --test clickhouse -- --exact
  - cargo test --package clickhouse-rs --features async_std --no-default-features --test clickhouse -- --exact
  - |
      if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
        cargo clippy --all-targets -- -D warnings;
      fi
after_success:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls --exclude-pattern target,tests;
      fi